name: efficient_infra_ui_example
description: Demonstrates how to use the efficient_infra_ui plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.5.1
  flutter:
    sdk: flutter
  efficient_infra_ui:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
