name: efficient_infra_ui
description: efficient ui library
version: 0.0.2
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
#  efficient_sdk:
#    path: ../efficient_sdk
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  bitsdojo_window: ^0.1.2
  flutter_svg: ^1.1.3
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.sr.efficient_infra_ui
        pluginClass: EfficientInfraUiPlugin
      ios:
        pluginClass: EfficientInfraUiPlugin
      windows:
        pluginClass: EfficientInfraUiPluginCApi
