name: efficient_infra_ui
description: efficient ui library
version: 0.0.6
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  get: ^4.5.1
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  bitsdojo_window: ^0.1.0
  flutter_svg: ^1.0.0
  fl_chart: ^0.55.1
  flutter_advanced_networkimage_2: ^2.0.1
#  qr_code_scanner: ^0.0.1
  plugin_platform_interface: ^2.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.sr.efficient_infra_ui
        pluginClass: EfficientInfraUiPlugin
      ios:
        pluginClass: EfficientInfraUiPlugin
      windows:
        pluginClass: EfficientInfraUiPluginCApi
